use_frameworks!

platform :ios, '9.0'

target 'LanguageTool_Example' do
  pod 'LanguageTool', :path => '../'

  target 'LanguageTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
